server:
  port: 8762

spring:
  application:
    name: nativeconfigserver
  profiles:   #本地获取配置
    active: native
  cloud:
    config:
      server:
        native:   #本地配置文件路径: classpath == java.resources
          search-locations: classpath:/shared


